dist: trusty

language: perl

perl:
  - '5.26'

services:
  - mysql

env:
  matrix:
    - COVERALLS=true
  global:
    - secure: Ju069PzB8QZG3302emIhyCEEQfVfVsiXy0nGcR6hue+vW9nE82NnOEZHbZIwUCXEjUaZRMVQ31Em70Ky22OrLK4D59bs2ClH21u8URDGD/cn7JNPGWFrgxuaXQKMQrw72doeB0+w1+ShURtqM41vITjinyU3y34RZ1NcbDwYSZI=

sudo: false

matrix:

addons:
  apt:
    packages:
      - unzip

before_install:
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git

install:
  - cpanm -v --installdeps --notest .
  - cpanm -n Devel::Cover::Report::Coveralls
  - cp travisci/MultiTestDB.conf.travisci  modules/t/MultiTestDB.conf
  - cp travisci/testdb.conf.travisci  testdb.conf
  - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: mSNxOSxwjk9915VYwV8zBK86m+KGEjg80m1gdk3ugbP+l5MN1go/Yejn1IiR/2H9GVYa25k2OzgSd2DeD/Z9iNQrr9aVYCcVn6AW0QHLOSMGi3Eexj3xYqc/9QGZ9l1ovkGRDk/azviOxcCQF3rfW5L9czgYq7DeAUMpw6658ANi0TdxDUlgpVeLXlRlCOE0UTEcEbQnEINF7HIE+qcR6sohgwvy4fQVBTMCWOXqDKDiPEx0DcmX0k+DSR/upkyKAeEtYTx+0HyUeJgEw0bc9jEdSPD+EKRiXefI7r7uuNp7sxIV9vIfZKUNW+LQJKM5rKb8GOBnuSzcv5ML690co+w83c89PXUcgFJRCzmIzLVxQHIQ9c/zBSEBdY5y0VVBKIEnfeTNTBkVayQyhk8N8nkSb5l+dgvtAbYO/T3elGNfIMDVPQivlAfGQKoQFV0WN2puGoug3zLBTcRvqlfAHofHHlSbdxG5kJI8g7LQLmrv6ox1VU3/AqYXuxxY2vLuKX9fhbqwacS6SVjYMKMQcVK22xJ92jMK4mobs8yeDfE9YrI9WA7kWs1aP9sXMmRt+8Nz06+MNw+ZGSGYUc7Uwoj9wP3cbdfYdWYLWSNj+5TzMasHmtjYZwKaxyLBWbg5PHox8U+0p1SdygQKV2ZWkz/U+eNDFj3eJA68IC2jceQ=
    on_failure: change
